self-hosted-runner:
  labels:
    - builder
    - builder-aarch64
    - func-tester
    - func-tester-aarch64
    - fuzzer-unit-tester
    - style-checker
    - style-checker-aarch64
    - release-maker
